#!/usr/bin/env python3
"""
build.py -- inline TOOL-EEG-022 into one self-contained .html file.

WHY THIS EXISTS.  The tool is written as ES modules because the study runner will reuse
protocol.js, transport.js and sinks.js unchanged, and a single 1200-line file would not
survive that.  But a browser will not load a module FILE from a `file://` page: the module
fetch is blocked by CORS, so a double-clicked index.html shows a blank screen.

An INLINE `<script type="module">` has nothing to fetch and runs fine from `file://`, and
Chromium treats `file://` as a secure context, so Web Serial works.  So this script
concatenates the modules in dependency order, strips the import/export keywords, and drops
the result into the page as one inline module.

The output is the deliverable an operator receives:

    EEG-Connectivity-Test.html      one file, no install, no server, no build step
                                    Windows and macOS alike -- double-click it

Run:  python3 build.py
Licence: MIT.
"""
from __future__ import annotations

import datetime
import hashlib
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "EEG-Connectivity-Test.html"

# Dependency order.  protocol has no imports; sinks and transport use protocol;
# diagnostics uses all three; ui uses everything.
MODULES = ["js/protocol.js", "js/sinks.js", "js/transport.js", "js/diagnostics.js", "js/ui.js"]


def strip_module_syntax(src: str, name: str) -> str:
    """Remove import statements and the `export` keyword.

    Everything ends up in one scope, so imports are unnecessary and exports are harmless to
    drop.  This is deliberately a small, dumb transform -- if it ever needs to be clever,
    that is the signal to ship a real bundler instead of pretending.
    """
    # whole-line imports, including multi-line braced ones
    src = re.sub(r"^\s*import\s+[^;]*?;\s*$", "", src, flags=re.M | re.S)
    # `export const`, `export function`, `export class`, `export default`
    src = re.sub(r"^\s*export\s+(?=(const|let|var|function|class|async))", "", src, flags=re.M)
    src = re.sub(r"^\s*export\s+default\s+", "", src, flags=re.M)
    # a bare `export { a, b };` block
    src = re.sub(r"^\s*export\s*\{[^}]*\}\s*;\s*$", "", src, flags=re.M)
    if re.search(r"^\s*(import|export)\s", src, flags=re.M):
        leftover = [ln for ln in src.splitlines() if re.match(r"\s*(import|export)\s", ln)]
        raise SystemExit(
            f"build.py: {name} still has module syntax after stripping, which would break "
            f"the inline bundle:\n  " + "\n  ".join(leftover[:5]))
    return src


def main() -> int:
    page = (HERE / "index.html").read_text(encoding="utf8")

    parts = []
    for m in MODULES:
        p = HERE / m
        if not p.exists():
            raise SystemExit(f"build.py: {m} is missing")
        body = strip_module_syntax(p.read_text(encoding="utf8"), m)
        parts.append(f"/* ===== {m} ===== */\n{body}")

    bundle = "\n\n".join(parts) + "\n\nboot();\n"

    # Replace the module loader with the inlined bundle.
    loader = re.search(r'<script type="module">.*?</script>', page, re.S)
    if not loader:
        raise SystemExit("build.py: could not find the module <script> block in index.html")

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (f"<!-- TOOL-EEG-022, built from source by webtest/build.py on {stamp}.\n"
              f"     Do not edit this file: edit webtest/js/*.js and rebuild, or the source\n"
              f"     and the deliverable will disagree. -->\n")
    page = page.replace(loader.group(0),
                        header + '<script type="module">\n' + bundle + '</script>')

    # A self-contained file must be genuinely self-contained.
    for bad in re.findall(r'(?:src|href)="(?!data:)([^"#][^"]*)"', page):
        if not bad.startswith(("http://", "https://")):
            raise SystemExit(f"build.py: the bundle still references a local file: {bad}")
    if "http://" in page or "https://" in page:
        refs = set(re.findall(r'(?:src|href)="(https?://[^"]+)"', page))
        if refs:
            raise SystemExit(f"build.py: the bundle loads something from the network: {refs}")

    OUT.write_text(page, encoding="utf8")
    digest = hashlib.sha256(OUT.read_bytes()).hexdigest()
    kb = OUT.stat().st_size / 1024
    print(f"  {OUT.name}  {kb:.1f} kB")
    print(f"  sha256 {digest}")
    print(f"  {len(MODULES)} modules inlined; no external references")
    return 0


if __name__ == "__main__":
    sys.exit(main())
