/*
 * board_pins.h -- EEG-CAR-01 Rev B pin map for FW-EEG-001.
 *
 * GENERATED by package_v2.4/tools from design.py.  Do not edit by hand: edit design.py
 * and regenerate, so the firmware and the board can never disagree.
 *
 * ECO-EEG-009: the Rev A map used GPIO35, 36 and 37 for the contact-light shift
 * register.  Those three pins carry the octal PSRAM on the ESP32-S3-DevKitC-1-N16R8
 * and are NOT CONNECTED on this carrier.  GPIO45 is the VDD_SPI strapping pin and is
 * also left open.  microSD is one-bit SDMMC for the same reason.
 *
 * Licence: MIT (firmware).
 */
#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#define BOARD_REV        "B"
#define BOARD_NAME       "EEG-CAR-01"

#define PIN_SR_LATCH     0    /* J7.14  net LED_SR_LATCH */
#define PIN_I2C_SDA      1    /* J7.4   net SDA */
#define PIN_I2C_SCL      2    /* J7.5   net SCL */
#define PIN_ENV_CMP      3    /* J6.13  net ENV_CMP */
#define PIN_BTN_A        4    /* J6.4   net BTN_A */
#define PIN_BTN_B        5    /* J6.5   net BTN_B */
#define PIN_BTN_STOP     6    /* J6.6   net BTN_STOP */
#define PIN_I2S_DIN      7    /* J6.7   net I2S_DIN */
#define PIN_I2S_LRCK     8    /* J6.12  net I2S_LRCK */
#define PIN_I2S_DOUT     9    /* J6.15  net I2S_DOUT */
#define PIN_ADS_CS       10   /* J6.16  net CS */
#define PIN_ADS_MOSI     11   /* J6.17  net MOSI */
#define PIN_ADS_SCLK     12   /* J6.18  net SCLK */
#define PIN_ADS_MISO     13   /* J6.19  net MISO */
#define PIN_ADS_DRDY     14   /* J6.20  net DRDY */
#define PIN_ADS_START    15   /* J6.8   net START */
#define PIN_ADS_RESET    16   /* J6.9   net RESET */
#define PIN_I2S_MCLK     17   /* J6.10  net I2S_MCLK */
#define PIN_I2S_BCLK     18   /* J6.11  net I2S_BCLK */
#define PIN_USB_DN       19   /* J7.20  net USB_DN */
#define PIN_USB_DP       20   /* J7.19  net USB_DP */
#define PIN_MIC_MUTE     21   /* J7.18  net MIC_MUTE */
#define PIN_SD_CMD       38   /* J7.10  net SD_CMD */
#define PIN_SD_CLK       39   /* J7.9   net SD_CLK */
#define PIN_SD_D0        40   /* J7.8   net SD_D0 */
#define PIN_SR_DATA      41   /* J7.7   net LED_SR_DATA */
#define PIN_SR_CLK       42   /* J7.6   net LED_SR_CLK */
#define PIN_UART0_TX     43   /* J7.2   net UART_TX */
#define PIN_UART0_RX     44   /* J7.3   net UART_RX */
#define PIN_VBUS_DET     46   /* J6.14  net VBUS_DET */
#define PIN_CHG_CE       47   /* J7.17  net CHG_CE */
#define PIN_LED_V        48   /* J7.16  net LED_PWM */

/* Header positions that MUST remain unconnected on this hardware */
#define PIN_RESERVED_PSRAM_D5   35
#define PIN_RESERVED_PSRAM_D6   36
#define PIN_RESERVED_PSRAM_D7   37
#define PIN_RESERVED_VDD_SPI    45

/* Front end */
#define N_CH            16
#define N_DEV            2
#define ADS_GAIN_EEG    24
#define ADS_GAIN_EMG    12
#define ADS_GAIN_ENV     1

/* Contact lights: eight two-lead bicolour LEDs between LEDn and the LED_V common.
 * Phase A drives LED_V high and the wanted sites low  -> green.
 * Phase B drives LED_V low  and the wanted sites high -> red.
 * Alternating above 100 Hz shows amber.  At reset LED_V is an input, so nothing can
 * light whatever the shift register contains -- that is the dark-at-boot guarantee. */
#define N_LIGHTS         8
#define LIGHT_PHASE_HZ 240

#endif /* BOARD_PINS_H */
