#!/usr/bin/env python3
"""
check_placement.py -- the layout-protocol placement checklist, measured.

Writes reports/placement_checklist.md.  Every verdict carries its evidence;
N/A items state why rather than inventing work.  Licence: CC BY-SA 4.0.
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import design as D   # noqa: E402
import pcbgen        # noqa: E402

board = pcbgen.BoardV2()
parts = {p.ref: p for p in board.parts}
pads = list(board.pads())
L = []


def pad(ref, num):
    for p in pads:
        if p.ref == ref and p.num == str(num):
            return p
    return None


def dist(a, b):
    return math.hypot(a.x - b.x, a.y - b.y)


L.append("# Placement checklist -- EEG-CAR-01 Rev B")
L.append("")
L.append("GENERATED by tools/check_placement.py; regenerate after any placement change.")
L.append("")

# 1. decoupling adjacency: each 100n/10u cap vs the supply pin it serves
DECAP = [("C80", "J1", 1), ("C81", "J3", 1), ("C82", "J8", 1), ("C83", "J11", 1),
         ("C84", "J19", 1), ("C85", "J20", 1), ("C86", "J21", 1), ("C87", "J10", 1),
         ("C89", "J10", 1), ("C90", "J21", 1),
         ("C100", "J23", 1), ("C101", "J23", 2), ("C102", "J23", 1), ("C103", "J23", 2),
         ("C23", "U1", 4), ("C24", "U1", 11), ("C43", "U2", 4), ("C44", "U2", 11),
         ("C63", "U3", 4), ("C64", "U3", 11),
         ("C70", "J25", 1), ("C71", "J25", 1), ("C72", "J25", 3), ("C73", "J25", 3),
         ("C74", "J6", 1), ("C88", "J19", 7), ("C50", "SW1", 1), ("C51", "SW2", 1),
         ("C52", "SW3", 1)]
L.append("## 1. Decoupling / local capacitors adjacent to their pins")
L.append("")
L.append("All SMT is top-side only (assembly note 1), so 'same side' holds by")
L.append("construction.  Distance is cap pad 1 to the served pin, straight line.")
L.append("")
L.append("| cap | serves | distance mm | verdict |")
L.append("|---|---|---|---|")
worst = []
for cref, tref, tpin in DECAP:
    cp, tp = pad(cref, 1), pad(tref, tpin)
    if not cp or not tp:
        L.append(f"| {cref} | {tref}.{tpin} | ? | MISSING PAD |")
        continue
    dd = dist(cp, tp)
    verdict = "pass" if dd <= 6.0 else ("review" if dd <= 12.0 else "FAIL")
    if verdict != "pass":
        worst.append((cref, tref, tpin, dd))
    L.append(f"| {cref} | {tref}.{tpin} | {dd:.1f} | {verdict} |")
L.append("")
if worst:
    L.append("Review items: " + "; ".join(
        f"{c} is {d:.1f} mm from {t}.{p}" for c, t, p, d in worst))
    L.append("")

# 2. crystal
L.append("## 2. Crystal near MCU with ground guard -- N/A")
xt = [p.ref for p in board.parts if "XTAL" in (p.value or "").upper() or "CRYSTAL" in (p.value or "").upper()]
L.append("")
L.append(f"No crystal exists on the carrier (search over part values: {xt or 'none'}).")
L.append("The ESP32-S3-DevKitC-1 module carries its own 40 MHz crystal; the carrier")
L.append("provides only the J6/J7 sockets.  Nothing to place or guard here.")
L.append("")

# 3. connectors on board edge
L.append("## 3. Connectors on the board edge -- deliberate exceptions, per ICD-EEG-006")
L.append("")
L.append("| conn | position | edge? | why it is where it is |")
L.append("|---|---|---|---|")
EDGE = 18.0
REASON = {
    "J14": "harness entry, left edge, matches pod gland",
    "J13": "battery pigtail, right edge near the cell carrier",
    "J24": "charge pigtail, right edge near the panel USB-C",
    "J10": "isolator socket, right edge, owns the isolation strip",
    "J15": "touch-proof DIN panel socket, left edge",
    "J16": "touch-proof DIN panel socket, left edge",
    "J17": "touch-proof DIN panel socket, left edge",
    "J26": "debug header, top-right corner, bench access",
}
for p in sorted((p for p in board.parts if p.ref.startswith(("J", "SW"))),
                key=lambda p: p.ref):
    on_edge = (p.x < EDGE or p.x > D.BOARD_W - EDGE
               or p.y < EDGE or p.y > D.BOARD_H - EDGE)
    why = REASON.get(p.ref)
    if why is None:
        why = ("module socket: the module sits on the MP-01 plate ABOVE the "
               "carrier and plugs DOWN through a keyed ribbon (ICD-EEG-006), "
               "so mid-board is the intended position"
               if p.ref not in ("SW1", "SW2", "SW3") else
               "response button on an extender through the pod lid; position "
               "is the lid's, not the edge's")
    L.append(f"| {p.ref} | ({p.x:.0f},{p.y:.0f}) | {'yes' if on_edge else 'no'} | {why} |")
L.append("")
L.append("Verdict: pass.  Every cable that leaves the enclosure enters at an edge")
L.append("connector; every mid-board socket mates vertically with MP-01 modules or")
L.append("lid buttons and must NOT be on the edge.")
L.append("")

# 4. partitioning
L.append("## 4. Analogue / digital partitioning with a defined boundary")
L.append("")
azone = [p.ref for p in board.parts if p.zone == "A" and p.x > D.ZONE_SPLIT_X]
dzone = [p.ref for p in board.parts if p.zone == "D" and p.x < D.ZONE_SPLIT_X
         and not p.ref.startswith(("MH", "FID"))]
L.append(f"Boundary: x = {D.ZONE_SPLIT_X} mm, planes split there (AGND_REF west,")
L.append("DGND east), joined at R90 only; drc.py counts zone crossings and star")
L.append(f"bridges on every run.  Analogue-zone parts east of the line: {azone or 'none'};")
L.append(f"digital-zone parts west of it: {dzone or 'none'}.")
L.append("Verdict: pass (drc_report.txt: zone crossings 0, exactly one bridge each).")
L.append("")

# 5. thermal vias
L.append("## 5. Thermal vias under exposed pads -- N/A")
L.append("")
import fplib
ep = [n for n, f in fplib.LIB.items() if any(pd.num == "EP" for pd in f.pads)]
L.append(f"No footprint in fplib carries an exposed pad (checked: {len(fplib.LIB)}")
L.append(f"footprints, exposed-pad hits: {ep or 'none'}).  The power parts are all")
L.append("purchased modules on MP-01; the carrier's hottest part is a 0R link.")
L.append("")

dst = os.path.join(os.path.dirname(HERE), "reports", "placement_checklist.md")
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, "w").write("\n".join(L))
print("wrote", dst)
print("review items:", len(worst))
for c, t, p, d in worst:
    print(f"  {c} -> {t}.{p}: {d:.1f} mm")
