#!/usr/bin/env python3
"""
emit_rule_sheet.py -- LAY-EEG-034, the carrier layout rule sheet, generated.

It is a controlled document and it is generated, which is not a contradiction: what
`tools/rules.py` holds as data -- the eight net classes, their minima, their layer and
via restrictions, the areas, the geometry rules -- is transcribed here rather than
retyped, so the sheet the contractor signs against and the `.kicad_dru` the contractor's
DRC runs cannot disagree.  The prose around the tables is written and is edited here.

Writes docs/LAY-EEG-034_RevA_carrier_layout_rule_sheet.md.  The .docx and .pdf come from
tools/make_docs.py like every other document.

Licence: CC BY-SA 4.0.
"""
from __future__ import annotations
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import design as D          # noqa: E402
import rules                # noqa: E402

OUT = os.path.join(PKG, "docs", "LAY-EEG-034_RevA_carrier_layout_rule_sheet.md")


def build():
    L = []
    a = L.append
    a("# Carrier Layout Rule Sheet -- EEG-CAR-01 Rev C")
    a("")
    a("**Document:** LAY-EEG-034  **Revision:** A  **Date:** 8 September 2026")
    a("**Issued by:** TI One Voice research programme (one.witysk.org), Brussels, "
      "Belgium")
    a("**Licence:** CC BY-SA 4.0")
    a("**Governing documents:** DSN-EEG-003 Rev C, then RFQ-EEG-001 Rev E, then "
      "ICD-EEG-006 Rev B.")
    a("**Generated by:** `tools/emit_rule_sheet.py` from `tools/rules.py`. The tables "
      "are not typed.")
    a("")
    a("## 1. Scope and precedence")
    a("")
    a("This sheet is the rule set for the placement and routing of **EEG-CAR-01 Rev C**, "
      "and it is **part of the order specification**. A departure from it is a layout "
      "error and is corrected at no charge, not a change request.")
    a("")
    a("`tools/design.py` governs. Where this sheet and `design.py` disagree, `design.py` "
      "is right and this sheet is regenerated. Where this sheet and "
      "`kicad/EEG-CAR-01_RevC.kicad_dru` disagree, both are wrong until regenerated: "
      "they come from one source, `tools/rules.py`.")
    a("")
    a("**Nothing in this package has been manufactured or measured, and no safety "
      "engineer has reviewed this design.**")
    a("")
    a("## 2. Board and stack-up")
    a("")
    a("The full specification is **DSN-EEG-003 Rev C section 3.2** and is not restated. "
      "The four lines a layout engineer needs:")
    a("")
    a(f"- **{D.BOARD_W:.1f} x {D.BOARD_H:.1f} mm**, rectangular, no cut-outs, no slots.")
    a("- **Four layers**: L1 signal, L2 reference plane, L3 reference plane, L4 signal. "
      "1.60 mm +/- 10 % finished, FR-4 Tg >= 150 C, 1 oz outer and 0.5 oz inner copper, "
      "ENIG.")
    a(f"- **Through vias only**, {rules.VIA['pad']:.2f} mm pad on a "
      f"{rules.VIA['drill']:.2f} mm finished hole, tented both sides. No blind, buried, "
      f"back-drilled, filled or plugged via anywhere.")
    a(f"- Board floor **{rules.MIN_TRACK:.2f} mm track / {rules.MIN_CLEARANCE:.2f} mm "
      f"clearance**, {rules.EDGE_CLEARANCE:.2f} mm copper to the board edge, "
      f"{rules.NPTH_CLEARANCE:.2f} mm copper to a non-plated hole. Section 5 is stricter "
      f"per class and section 5 wins.")
    a("")
    a("## 3. Zoning and star points")
    a("")
    a("**DSN-EEG-003 Rev C section 3.3 rules 1 and 2**, cited and not restated. In this "
      "sheet's terms:")
    a("")
    a(f"- The board is two zones split at **x = {D.ZONE_SPLIT_X:.1f} mm**: analogue "
      f"left, digital right. No digital-class net may be routed into the analogue zone "
      f"and no analogue-class net out of it. **One signal crosses by design** -- "
      f"`CMP_RAW`, the comparator output, which must reach a 3.3 V GPIO and does so "
      f"through R83 and the D23 clamp.")
    a("- `AGND_REF` is the analogue **0 V mid-rail and is not ground**. It is poured on "
      "L2 and L3 over the whole analogue zone; `DGND` is poured over the digital zone on "
      "the same two layers. L1 and L4 carry signals, which is why the board has four "
      "layers.")
    a("- **`AGND_REF` joins `DGND` at R90 and nowhere else. `HARN_SHIELD` joins `DGND` "
      "at R91 and nowhere else.** Both are 0 R 0603 parts and neither may become a copper "
      "bridge: each has to lift for a leakage measurement and refit. A second path of any "
      "kind, on any layer, is a layout error.")
    a("")
    a("## 4. Isolation keep-out")
    a("")
    x0, y0, x1, y1 = rules.ISOLATION_KEEPOUT
    a(f"**DSN-EEG-003 Rev C section 3.3 rule 4.** The strip **x >= {x0:.1f} mm, "
      f"y = {y0:.1f} to {y1:.1f} mm** carries **no copper on any of the four layers**, "
      f"and no via, no pad and no footprint. It is `ISOLATION_KEEPOUT` in the board file "
      f"and in the `.kicad_dru`.")
    a("")
    a("The 2.5 kV barrier itself is **on the purchased ADuM4160 module at J10**, not on "
      "this board; nothing on the carrier is on the host side. What the carrier owes the "
      "barrier is to keep out from under the module's host half. **The rule is enforced "
      "against copper EDGES and not track centrelines**, which is what earlier revisions "
      "of this programme's own check got wrong.")
    a("")
    a("## 5. Net classes")
    a("")
    a(f"Eight classes over all **{len(set(D.N.values()))}** nets. **Minimum** is a floor "
      f"and a conductor below it is an error; **preferred** is what to route at wherever "
      f"the board allows it. `Vias` says whether the class may have one at all. "
      f"`Confirm` names the **columns of that row** that are proposals of this programme "
      f"and not transcriptions from a governing document -- if one of those is "
      f"unroutable, say so at the placement gate rather than relaxing it silently. "
      f"Everything not named there is a requirement.")
    a("")
    a("| Class | Nets | Width min / pref (mm) | Clearance min / pref (mm) | Layers | "
      "Vias | Confirm |")
    a("|---|---|---|---|---|---|---|")
    for r in rules.summary_table():
        conf = ", ".join(f"**{c}**" for c in r["confirm"]) if r["confirm"] else "no"
        a(f"| `{r['name']}` | {r['nets']} | {r['min_width']:.2f} / "
          f"{r['pref_width']:.2f} | {r['min_clearance']:.2f} / "
          f"{r['pref_clearance']:.2f} | {r['layers']} | {r['vias']} | "
          f"{conf} |")
    a("")
    cited = [r for r in rules.summary_table() if r["cites"]]
    for r in cited:
        a(f"**`{r['name']}`** -- every column of that row except "
          f"{', '.join(r['confirm'])} is a requirement transcribed from "
          f"{r['cites']}, and is not open for confirmation.")
    a("")
    a("Where the numbers come from:")
    a("")
    for c in rules.CLASSES:
        a(f"- **`{c.name}`** -- {' '.join(c.why.split())}")
    a("")
    a("The class of every net is in `kicad/EEG-CAR-01_RevC.kicad_pro` and, in a form a "
      "person can read, in `constraints/nets.md`.")
    a("")
    a("## 6. Geometry rules")
    a("")
    a("These are the seven findings an external layout engineer made against Rev B "
      "between 3 and 5 September 2026 (ECO-EEG-016 section 2, ECO-EEG-030), and they "
      "are why this sheet exists. **Six are rules; the seventh was a missing check and "
      "is section 7.** The right-hand column is not a formality: two of them KiCad "
      "cannot check, and this programme checks those itself on the geometry that comes "
      "back.")
    a("")
    a("| # | Rule | Checked by |")
    a("|---|---|---|")
    a("| 1 | **No drill inside a pad.** No via inside an SMD pad or within "
      f"{rules.GEOMETRY['via_to_smd_pad_min']:.2f} mm of one, on its own net or any "
      "other | KiCad DRC (`no_via_in_smd_pad`) **and** our DRC on return |")
    a("| 2a | **No dangling track end.** Every track end lands on a pad, a via, another "
      "track or a pour | KiCad DRC built-in `track_dangling`, raised to **error** in the "
      "project file, **and** our DRC on return |")
    a("| 2b | **No redundant copper path.** Not more than one copper path between the "
      "same two points on a net, outside a plane | KiCad DRC built-ins **and** our DRC "
      "on return |")
    a("| 3 | **45-degree routing.** No angle below "
      f"{rules.GEOMETRY['min_segment_angle_deg']:.0f} degrees between two segments of "
      "one track, and every segment on a 0, 45, 90 or 135 degree axis | **NOT CHECKABLE "
      "IN KiCad** -- there is no constraint for it. **Verified by our DRC on the "
      "returned board** |")
    a("| 4 | **Pad-centre entry.** A track entering a pad has its centreline within "
      f"{rules.GEOMETRY['pad_entry_frac'] * 100:.0f} % of the pad's minor dimension of "
      "the pad centre | **NOT CHECKABLE IN KiCad.** **Verified by our DRC on the "
      "returned board** |")
    a("| 5 | **Net classes.** Section 5 above: width, clearance, permitted layers and "
      "the via rule, per class | KiCad DRC (`width_*`, `clearance_*`, `layers_*`, "
      "`no_vias_*`) **and** our DRC on return |")
    a("| 6 | **Zoning, star points and the isolation keep-out.** Sections 3 and 4 | "
      "KiCad DRC through the rule areas **and** our DRC on return |")
    a("")
    a("`kicad/EEG-CAR-01_RevC.kicad_dru` is the machine-readable half of this table and "
      "carries 37 rules. Load it with the project; it is not optional.")
    a("")
    a("**Two more, from DSN-EEG-003 section 3.3, that are not new and are easy to miss.** "
      "Rule 7: **no via inside the outline of J2, J4, J23 or J29**, the analogue module "
      "connectors -- they are `NO_VIA_J*` rule areas in the board file. Rule 5: "
      "**`USB_DP` and `USB_DN` are a 0.30 mm pair on 0.35 mm spacing on L1 directly over "
      "the L2 DGND plane**, about 95 ohm differential. No coupon and no impedance report "
      "are required and none is wanted.")
    a("")
    a("## 7. Placement")
    a("")
    a("**Placement drives via count, must precede routing, and is reviewed before "
      "routing starts.** That is the reviewer's own principle and this programme has "
      "adopted it.")
    a("")
    a("1. **The thirty connectors J1 to J30 are LOCKED**, with MH1-MH4 and FID1-FID3. "
      "The pod, the module plate MP-01 and the harness fix them and they may not move. "
      "**37 footprints are locked in `kicad/EEG-CAR-01_RevC.kicad_pcb` and the lock is "
      "the specification.** Everything else sits at its Rev B coordinate, unlocked, and "
      "is yours to place.")
    a("2. **Each of the sixteen protection networks is placed in a straight line -- "
      "resistor, then clamp, then filter capacitor -- running from the harness towards "
      "the module** (DSN-EEG-003 section 3.3 rule 3). The schematic is drawn that way so "
      "that the intent is visible: sheet `50_harness_input`.")
    a("3. **Envelope decoupling within 3 mm** of pins 4 and 11 of each OPA4376.")
    a("4. **Every electrode-class net is routed on L1 with the reference plane "
      "continuous beneath it.** That is what the `ELECTRODE` class's L1-only, no-via row "
      "in section 5 means, and it is DSN-EEG-003 section 3.3 rule 3 read literally.")
    a("5. **The placement stage is delivered as a `.kicad_pcb` with the STEP bodies "
      "loaded**, and it passes a 3D collision check with the module bodies installed "
      "before it is delivered. The bodies are in `mech/step/`.")
    a("6. **We confirm the placement before routing is confirmed.** The review is a "
      "written findings list by net, pad pair and coordinate, capped at four to six "
      "hours, under RFQ-EEG-002A as re-scoped by ECO-EEG-030.")
    a("")
    a("**One open item that belongs to this programme and not to the layout "
      "contractor**, stated here because a placement reviewer will meet it: "
      "`mech/EEG-CAR-01_RevC_collision_check.txt` reports that the twelve modules do not "
      "fit on MP-01 -- 17 356 mm2 of declared envelopes into 12 409 mm2 of plate -- and "
      "that the plate's DevKit opening is 2 mm shorter than the DevKit. **Neither is a "
      "carrier layout question and neither blocks this order**; both are recorded in "
      "ASM-EEG-023 under MECH-D6-MODULE-ENVELOPES.")
    a("")
    a("## 8. Deliverables expected back")
    a("")
    a("1. **The KiCad project**, at the version agreed at the order -- `.kicad_pro`, "
      "`.kicad_sch` set, `.kicad_pcb`, and the `.kicad_dru` unchanged.")
    a("2. **A DRC run against this sheet**, clean, taken before handover, with the "
      "report. Sections 5 and 6 are the rule set; `.kicad_dru` is loaded.")
    a("3. **Gerber X2**, one file per layer, with file attributes.")
    a("4. **Excellon 2 drill files**, plated and non-plated separately.")
    a("5. **IPC-D-356A netlist** for the bare-board electrical test.")
    a("6. **CPL** for the surface-mount parts and, separately, the through-hole parts.")
    a("7. **Fabrication and assembly drawings.**")
    a("")
    a("On return, this programme runs its own DRC over the geometry -- including rules 3 "
      "and 4 of section 6, which KiCad cannot check -- and grades the result. The tool "
      "is `tools/drc.py` with `tools/drc_geometry.py`, it is in the repository, and it "
      "is the same one that regraded Rev B and found 1 311 occurrences of these six "
      "rules in a board its own report called clean.")
    a("")
    a("---")
    a("")
    a("**Contact.** Stephane van der Aa, Founder, TI One Voice -- one.witysk.org -- "
      "stephane@stepvda.com -- +32 493 70 16 01")
    return "\n".join(L) + "\n"


def main(verbose=True):
    text = build()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    if verbose:
        print("   ", os.path.relpath(OUT, PKG),
              f"({len(text.splitlines())} lines)")
    return [OUT]


if __name__ == "__main__":
    main()
