#!/usr/bin/env python3
"""
emit_netclass_table.py -- write constraints/nets.md from design.py.

design.py is the machine-readable constraint source (NETCLASS, netclass_of,
zone sets, pour spec); this emits the human-readable classification table the
layout protocol asks for.  Regenerate after any netlist or class change:

    python3 tools/emit_netclass_table.py

Licence: CC BY-SA 4.0.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import design as D  # noqa: E402
import pcbgen       # noqa: E402

CLS_LABEL = {"ELECTRODE": "ANALOG (electrode)", "ANALOG": "ANALOG",
             "POWER_A": "PWR (analogue rails)", "POWER_D": "PWR/GND (digital)",
             "USB": "DIFF", "DEFAULT": "GPIO"}


def rows():
    board = pcbgen.BoardV2()
    nets = board.nets()
    prio_order = []
    import build_board as BB
    for n in BB.PRIORITY:
        if n in nets and n not in prio_order:
            prio_order.append(n)
    for n in sorted(nets):
        if n not in prio_order:
            prio_order.append(n)
    prio_rank = {n: i for i, n in enumerate(prio_order)}
    nprio = max(1, len(prio_order) - 1)
    out = []
    for net in sorted(nets):
        cls = D.netclass_of(net)
        w, c = D.NETCLASS[cls]
        # allowed layers / zone
        if net in ("DGND",):
            lay = "In1+In2 plane (digital side) + F/B stitching"
        elif net in ("AGND_REF",):
            lay = "In1+In2 plane (analogue side) + F/B stitching"
        elif net in D.ELECTRODE_NETS:
            lay = "F.Cu preferred (B.Cu fallback), analogue zone only"
        elif net in D.ANALOG_ZONE_NETS:
            lay = "F/B, analogue zone only (x < %.0f)" % D.ZONE_SPLIT_X
        elif net in D.DIGITAL_ONLY_NETS:
            lay = "F/B, digital zone only (x > %.0f)" % D.ZONE_SPLIT_X
        else:
            lay = "F/B, both zones"
        imp = "95 R diff pair (informative, no coupon)" if cls == "USB" else "-"
        if cls == "USB":
            grp = "USB pair; no formal tolerance (measured mismatch in DRC-era metrics)"
        elif net in ("SCLK", "MOSI", "MISO", "DRDY", "CS"):
            grp = "SPI group; DOCUMENTED intent 10 mm, NOT enforced by drc.py"
        else:
            grp = "-"
        p = 1 + (4 * prio_rank[net]) // nprio if net in prio_rank else 5
        out.append((net, CLS_LABEL[cls], f"{w:.2f}", f"{c:.2f}", imp, grp, lay, p,
                    len(nets[net])))
    return out


def main():
    lines = [
        "# Net classification -- EEG-CAR-01 Rev B",
        "",
        "GENERATED by tools/emit_netclass_table.py from tools/design.py.",
        "design.py is the machine-readable authority (NETCLASS, netclass_of,",
        "ELECTRODE_NETS, ANALOG_ZONE_NETS, DIGITAL_ONLY_NETS, POURS); this table",
        "is its human-readable rendering.  Edit design.py, then regenerate.",
        "",
        "Rules in force beyond the table: electrode copper keeps 0.35 mm to",
        "everything (drc.py); zone split at x = %.1f mm with AGND_REF/DGND" % D.ZONE_SPLIT_X,
        "planes joined at R90 only and HARN_SHIELD at R91 only; no via or",
        "bottom-layer copper under the module outlines of J2/J4/J23/J29;",
        "isolation strip x >= 141, y = 2..22 clear of copper on all layers.",
        "",
        "Priority is the routing order bucket (1 routes first).  One-pad NC_*",
        "nets are declared no-connects and are not routed.",
        "",
        "| net | class | width | clearance | impedance | length-match | allowed layers / zone | prio | pads |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    flagged = []
    for net, cls, w, c, imp, grp, lay, p, npads in rows():
        lines.append(f"| {net} | {cls} | {w} | {c} | {imp} | {grp} | {lay} | {p} | {npads} |")
        if net == "CMP_RAW":
            flagged.append((net, "crosses the zone split by declared design "
                                 "exception (comparator output to a 3V3 GPIO "
                                 "through R83/D23) -- confirmed intentional in "
                                 "design.py comments"))
        if net in ("HP_TAP", "VOICE_PRE", "ROOM_PRE"):
            flagged.append((net, "allowed in both zones: an audio-band analogue "
                                 "signal that must reach the codec (digital "
                                 "zone) and an envelope detector (analogue "
                                 "zone).  Deliberate, per RFQ E-11/E-12."))
    lines += ["", "## Flagged nets (reviewed, no open question)", ""]
    for n, why in flagged:
        lines.append(f"* **{n}** -- {why}")
    lines += ["", "## Known documentation defects", "",
              "* router.py's docstring claims SPI is length-matched within 10 mm; "
              "nothing measures it.  Electrically irrelevant at <= 8 MHz on a "
              "150 mm board, but the claim should be removed or the check added.",
              "* No length-match tolerance is stated anywhere for the USB pair; "
              "the fabrication notes call the impedance figure informative and "
              "waive the coupon.", ""]
    dst = os.path.join(os.path.dirname(HERE), "constraints", "nets.md")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, "w").write("\n".join(lines))
    print("wrote", dst, f"({len(rows())} nets)")


if __name__ == "__main__":
    main()
