#!/usr/bin/env python3
"""
footprint_audit.py -- check every reference designator's footprint against its
manufacturer part number, and its value against the part number where the part number
encodes one.  Writes docs/footprint_audit_RevC.md.

This exists because "BOM with verified footprints" was promised to a layout contractor
(ECO-EEG-030) and the BOM in the tree had at least three known errors and, when this
check was first run, a fourth nobody had found.  A footprint that does not match its
part number is not a documentation defect: it is a board that cannot be assembled.

What it checks, per designator:

  1  PACKAGE.  The package the part number encodes, against the footprint fitted.  The
     rules are per manufacturer and are written out below with the datasheet each one
     comes from; a part number no rule recognises is reported as UNRECOGNISED, never as
     a pass.
  2  WAYS.  For socket strips, the way count in the part number against the way count
     in the footprint name AND the pad count actually generated by fplib.
  3  VALUE.  For Vishay CRCW/TNPW and Murata GCM/GRM the part number encodes resistance
     or capacitance, tolerance, dielectric and voltage.  Those are decoded from the part
     number and compared with the value string, which is what a buyer reads.

A designator passes only if every check that applies to it passes.  Test points,
fiducials and mounting holes are fabricated features with no part number and are
reported as such rather than counted as passes.

Licence: CC BY-SA 4.0.
"""
from __future__ import annotations
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import design as D          # noqa: E402
import fplib                # noqa: E402

# --------------------------------------------------------------------------- datasheets
DS = {
    "vishay_crcw": "Vishay CRCW-e3 thick film chip resistor datasheet, document 20035, "
                   "part-number table",
    "vishay_tnpw": "Vishay TNPW-e3 thin film chip resistor datasheet, document 28776, "
                   "part-number table",
    "murata_cap": "Murata GRM/GCM chip monolithic ceramic capacitor part numbering, "
                  "catalogue C02E, part-numbering page",
    "murata_bead": "Murata chip ferrite bead part numbering and impedance map, "
                   "catalogue C31E pages 13 and 15",
    "nexperia_sot23": "Nexperia BAV99 (SOT-23) datasheet; BAT54S (SOT-23) datasheet; "
                      "PESD5V0S2BT (SOT-23) datasheet",
    "ti_pw": "TI OPA4376 datasheet SBOS406, package option addendum: PW (TSSOP-14) is "
             "the only package the quad is offered in",
    "ti_dbv": "TI TLV3201 datasheet SBOS589, package DBV (SOT-23-5)",
    "omron_b3f": "Omron B3F tactile switch datasheet: 6 x 6 mm models are B3F-1000 / "
                 "-3000 / -6000 (PCB pattern 6.5 x 4.5 mm); 12 x 12 mm models are "
                 "B3F-4000 / -5000 / -5001",
    "samtec_ssw": "Samtec SSW series 2.54 mm socket strip datasheet: SSW-1nn-01-G-S, "
                  "nn = positions, single row, vertical through-hole",
    "jst_ph": "JST PH series 2.00 mm connector datasheet: B2B-PH-K-S, 2 way, top entry",
    "bourns_mfmsmf": "Bourns MF-MSMF series resettable PTC datasheet: MSMF = 1206",
    "staubli_din": "Staubli / Multi-Contact touch-proof 1.5 mm socket to DIN 42802",
}

# --------------------------------------------------------------------------- decoders
MURATA_DIELECTRIC = {"5C": "C0G", "R7": "X7R", "R6": "X5R", "R1": "X5R", "C7": "X7R"}
MURATA_VOLTAGE = {"0J": "6.3V", "1A": "10V", "1C": "16V", "1D": "20V", "1E": "25V",
                  "1V": "35V", "1H": "50V", "1J": "63V", "2A": "100V"}
MURATA_TOL = {"B": "+/-0.10pF", "C": "+/-0.25pF", "D": "+/-0.5pF", "F": "1%",
              "G": "2%", "J": "5%", "K": "10%", "M": "20%"}
MURATA_SIZE = {"15": "0402", "18": "0603", "21": "0805", "31": "1206", "32": "1210"}
VISHAY_TOL = {"B": "0.1%", "D": "0.5%", "F": "1%", "Z0": "jumper"}


def _si(value_ohms):
    """Format ohms the way the value strings do: 68k, 4k99, 215k, 1M, 0."""
    if value_ohms == 0:
        return "0"
    for div, suf in ((1e6, "M"), (1e3, "k"), (1, "")):
        if value_ohms >= div:
            q = value_ohms / div
            if abs(q - round(q)) < 1e-9:
                return f"{int(round(q))}{suf}"
            whole = int(q)
            frac = round((q - whole) * 100)
            return f"{whole}{suf}{frac:02d}".rstrip("0") if suf else f"{q:g}"
    return f"{value_ohms:g}"


def decode_vishay(mpn):
    """-> (size_code, ohms, tolerance) or None."""
    m = re.match(r"^(CRCW|TNPW)(\d{4})([0-9RKM]{4})([A-Z]|Z0)", mpn)
    if not m:
        return None
    _, size, code, tol = m.groups()
    if code == "0000":
        return size, 0.0, VISHAY_TOL.get(tol, tol)
    mult = {"R": 1.0, "K": 1e3, "M": 1e6}
    for ch, mul in mult.items():
        if ch in code:
            a, b = code.split(ch, 1)
            digits = (a + "." + b) if b.strip("0") or b else a
            return size, float(digits) * mul, VISHAY_TOL.get(tol, tol)
    return size, float(code), VISHAY_TOL.get(tol, tol)


def decode_murata_cap(mpn):
    """-> (size_code, dielectric, voltage, farads, tolerance) or None."""
    m = re.match(r"^(GRM|GCM)(\d{2})(\d)([A-Z0-9]{2})([A-Z0-9]{2})(\d{3})([A-Z])", mpn)
    if not m:
        return None
    _, size, _th, diel, volt, cap, tol = m.groups()
    farads = int(cap[:2]) * (10 ** int(cap[2])) * 1e-12
    return (MURATA_SIZE.get(size, size), MURATA_DIELECTRIC.get(diel, diel),
            MURATA_VOLTAGE.get(volt, volt), farads, MURATA_TOL.get(tol, tol))


def decode_murata_bead(mpn):
    """-> (size_code, series, ohms_at_100MHz) or None."""
    m = re.match(r"^BLM(\d{2})([A-Z]{2})(\d{3})", mpn)
    if not m:
        return None
    size, series, imp = m.groups()
    ohms = int(imp[:2]) * (10 ** int(imp[2]))
    return MURATA_SIZE.get(size, size), series, ohms


def fmt_farads(f):
    for div, suf in ((1e-6, "u"), (1e-9, "n"), (1e-12, "p")):
        if f >= div - 1e-18:
            q = f / div
            return f"{q:g}{suf}"
    return f"{f:g}F"


# --------------------------------------------------------------------------- rules
def audit_one(ref, comp):
    """-> (verdict, package_note, value_note, datasheet) with verdict in
    PASS / FAIL / FEATURE / UNRECOGNISED."""
    mpn = comp["mpn"].strip()
    fp = comp["fp"]
    val = comp["val"]
    fpd = fplib.get(fp)
    npads = len([p for p in fpd.pads if p.kind != "np_thru_hole"])

    if mpn in ("", "-"):
        kind = ("test point" if fp.startswith("TestPoint") else
                "fiducial" if fp.startswith("Fiducial") else
                "mounting hole" if fp.startswith("MountingHole") else "no part number")
        return "FEATURE", f"{kind}: fabricated, not purchased", "", ""

    # ---- Vishay chip resistors
    if mpn.startswith("Vishay "):
        core = mpn[len("Vishay "):]
        d = decode_vishay(core)
        if not d:
            return "UNRECOGNISED", f"no Vishay rule matches {core}", "", ""
        size, ohms, tol = d
        ds = DS["vishay_tnpw"] if core.startswith("TNPW") else DS["vishay_crcw"]
        want_fp = f"R_{size}_" + {"0603": "1608Metric", "1206": "3216Metric"}.get(size, "?")
        pkg_ok = fp == want_fp
        pkg = (f"{core[:4]} size code {size} -> {want_fp}"
               if pkg_ok else f"part number is size {size} ({want_fp}); footprint is {fp}")
        want_val = _si(ohms)
        val_ok = val.split()[0].replace("R", "").lower().startswith(want_val.lower()) or \
            val.lower().startswith(want_val.lower())
        vnote = (f"{want_val} ohm {tol}" if val_ok else
                 f"part number encodes {want_val} ohm {tol}; value string says '{val}'")
        if pkg_ok and val_ok:
            return "PASS", pkg, vnote, ds
        return "FAIL", pkg, vnote, ds

    # ---- Murata capacitors and beads
    if mpn.startswith("Murata "):
        core = mpn[len("Murata "):]
        if core.startswith("BLM"):
            d = decode_murata_bead(core)
            if not d:
                return "UNRECOGNISED", f"no Murata bead rule matches {core}", "", ""
            size, series, ohms = d
            pkg_ok = fp == "L_0603_1608Metric" and size == "0603"
            pkg = (f"BLM size code -> {size}, series {series}" if pkg_ok else
                   f"part number is size {size}; footprint is {fp}")
            val_ok = str(ohms) in val.replace(" ", "") or f"{ohms}R" in val.replace(" ", "")
            vnote = (f"{ohms} ohm at 100 MHz" if val_ok else
                     f"part number encodes {ohms} ohm at 100 MHz; value says '{val}'")
            return ("PASS" if pkg_ok and val_ok else "FAIL"), pkg, vnote, DS["murata_bead"]
        d = decode_murata_cap(core)
        if not d:
            return "UNRECOGNISED", f"no Murata capacitor rule matches {core}", "", ""
        size, diel, volt, farads, tol = d
        pkg_ok = fp == "C_0603_1608Metric" and size == "0603"
        pkg = (f"size code -> {size}" if pkg_ok else
               f"part number is size {size}; footprint is {fp}")
        want = f"{fmt_farads(farads)} {diel} {volt}"
        got = val.replace("F", "").strip()
        val_ok = (fmt_farads(farads).lower() in got.lower()
                  and diel.lower() in got.lower()
                  and volt.lower().replace("v", "") in got.lower().replace("v", ""))
        vnote = want if val_ok else f"part number encodes {want}; value string says '{val}'"
        return ("PASS" if pkg_ok and val_ok else "FAIL"), pkg, vnote, DS["murata_cap"]

    # ---- Nexperia SOT-23
    if mpn.startswith("Nexperia "):
        core = mpn[len("Nexperia "):]
        known = {"BAV99,215": "SOT-23", "BAT54S,215": "SOT-23",
                 "PESD5V0S2BT,215": "SOT-23"}
        if core not in known:
            return "UNRECOGNISED", f"no Nexperia rule matches {core}", "", ""
        ok = fp == known[core]
        return ("PASS" if ok else "FAIL"), (f"{core} -> {known[core]}" if ok else
                                            f"{core} is {known[core]}; footprint is {fp}"), \
            "", DS["nexperia_sot23"]

    # ---- TI
    if mpn.startswith("TI "):
        core = mpn[len("TI "):]
        m = re.match(r"^(OPA4376AI|TLV3201AI)(PW|DBV|D)R?$", core)
        if not m:
            return "UNRECOGNISED", f"no TI rule matches {core}", "", ""
        dev, suf = m.groups()
        table = {"PW": ("TSSOP-14_4.4x5mm_P0.65mm", DS["ti_pw"]),
                 "DBV": ("SOT-23-5", DS["ti_dbv"]),
                 "D": ("SOIC-14_3.9x8.7mm_P1.27mm", DS["ti_pw"])}
        want, ds = table[suf]
        if dev == "OPA4376AI" and suf != "PW":
            return "FAIL", (f"suffix {suf} is not an OPA4376 package: the quad is made "
                            f"only in PW (TSSOP-14)"), "", DS["ti_pw"]
        ok = fp == want
        return ("PASS" if ok else "FAIL"), (f"{dev}{suf} -> {want}" if ok else
                                            f"{dev}{suf} is {want}; footprint is {fp}"), \
            "", ds

    # ---- Omron tactile switch
    if mpn.startswith("Omron B3F-"):
        num = mpn[len("Omron B3F-"):]
        family = num[0]
        body = {"1": "6 x 6 mm", "3": "6 x 6 mm side-operated", "6": "6 x 6 mm radial",
                "4": "12 x 12 mm", "5": "12 x 12 mm"}.get(family, "unknown")
        want6 = fp.startswith("SW_PUSH_6mm")
        ok = want6 and body.startswith("6 x 6")
        pkg = (f"B3F-{num} is {body}; footprint {fp} is the 6 x 6 mm 6.5 x 4.5 mm pattern"
               if ok else
               f"B3F-{num} is a {body} switch; footprint {fp} is the 6 x 6 mm "
               f"6.5 x 4.5 mm four-terminal pattern")
        return ("PASS" if ok else "FAIL"), pkg, "", DS["omron_b3f"]

    # ---- Samtec socket strips.  SSW-1nn-01-G-S: the leading 1 is the .100 in (2.54 mm)
    # centreline designator and nn is the positions per row, so SSW-112 is TWELVE ways
    # and not one hundred and twelve.
    if mpn.startswith("Samtec SSW-"):
        m = re.match(r"^Samtec SSW-1(\d{2})-01-G-S", mpn)
        if not m:
            return "UNRECOGNISED", f"no Samtec rule matches {mpn}", "", ""
        ways = int(m.group(1))
        m2 = re.match(r"^PinSocket_1x(\d{2})_P2\.54mm_Vertical$", fp)
        if not m2:
            return "FAIL", f"SSW-1{ways:02d} is a 1x{ways} socket; footprint is {fp}", "", \
                DS["samtec_ssw"]
        fways = int(m2.group(1))
        ok = ways == fways == npads
        return ("PASS" if ok else "FAIL"), \
            (f"SSW-1{ways:02d}-01-G-S -> 2.54 mm, 1x{ways}, {npads} pads generated" if ok else
             f"SSW-1{ways:02d} is {ways} ways; footprint is {fways} ways with {npads} pads"), \
            "", DS["samtec_ssw"]

    # ---- JST PH
    if mpn.startswith("JST B2B-PH-K"):
        ok = fp == "JST_PH_B2B-PH-K_1x02_P2.00mm_Vertical" and npads == 2
        return ("PASS" if ok else "FAIL"), \
            ("B2B-PH-K-S -> 2 way, 2.00 mm, top entry" if ok else
             f"B2B-PH-K-S is a 2-way 2.00 mm top-entry header; footprint is {fp}"), \
            "", DS["jst_ph"]

    # ---- Bourns PTC
    if mpn.startswith("Bourns MF-MSMF"):
        ok = fp == "R_1206_3216Metric"
        return ("PASS" if ok else "FAIL"), \
            ("MF-MSMF -> 1206 (3216 metric)" if ok else
             f"MF-MSMF is a 1206 device; footprint is {fp}"), "", DS["bourns_mfmsmf"]

    # ---- Staubli touch-proof socket
    if mpn.startswith("Staubli "):
        ok = fp == "DIN42802_1p5mm_Socket"
        note = ("SLB1,5-F / LB-I1,5 is a CLASS of touch-proof 1.5 mm socket, not a "
                "qualified PCB part: no drawing has been checked against this footprint "
                "and no sample has been approved (ICD-EEG-006 section 1, "
                "AVL-EEG-017 section 6.4). PATIENT-CONNECTED, not substitutable")
        return ("OPEN" if ok else "FAIL"), note, "", DS["staubli_din"]

    return "UNRECOGNISED", f"no rule matches manufacturer of {mpn!r}", "", ""


# --------------------------------------------------------------------------- report
def run():
    rows = []
    for ref in sorted(D.C, key=lambda r: (r[0], int("".join(c for c in r if c.isdigit()) or 0))):
        c = D.C[ref]
        verdict, pkg, vnote, ds = audit_one(ref, c)
        rows.append((ref, c["mpn"] or "-", c["fp"], c["val"], verdict, pkg, vnote, ds))
    return rows


def write_report(path=None):
    rows = run()
    path = path or os.path.join(PKG, "docs", "footprint_audit_RevC.md")
    tally = {}
    for r in rows:
        tally[r[4]] = tally.get(r[4], 0) + 1
    bad = [r for r in rows if r[4] in ("FAIL", "UNRECOGNISED")]
    open_ = [r for r in rows if r[4] == "OPEN"]

    with open(path, "w") as f:
        f.write("# Footprint versus part-number audit -- EEG-CAR-01 Rev C\n\n")
        f.write("**Generated by:** `tools/footprint_audit.py`, from `tools/design.py` and "
                "`tools/fplib.py`. Not edited by hand.\n")
        f.write(f"**Board:** {D.BOARD_NAME} Rev {D.REV_C}  **Date of this run:** "
                f"{D.DATE_C}\n")
        f.write("**Licence:** CC BY-SA 4.0\n\n")
        f.write("This is the file behind the phrase \"BOM with verified footprints\" in the "
                "layout-contractor input list of ECO-EEG-030. It checks the package the "
                "manufacturer part number encodes against the footprint fitted, the way "
                "count of every socket strip against the pads `fplib` actually generates, "
                "and -- for the Vishay and Murata part numbers, which carry it -- the "
                "value, tolerance, dielectric and voltage rating against the value string "
                "a buyer reads. A part number no rule recognises is reported as "
                "UNRECOGNISED and is **not** a pass.\n\n")
        f.write("| Verdict | Count | Meaning |\n|---|---|---|\n")
        f.write(f"| PASS | {tally.get('PASS', 0)} | package and value agree with the part "
                f"number |\n")
        f.write(f"| FAIL | {tally.get('FAIL', 0)} | they do not |\n")
        f.write(f"| OPEN | {tally.get('OPEN', 0)} | the part number is a class of part and "
                f"not a qualified part; the footprint cannot be checked against a drawing "
                f"until one is bought |\n")
        f.write(f"| UNRECOGNISED | {tally.get('UNRECOGNISED', 0)} | no decoding rule "
                f"matched |\n")
        f.write(f"| FEATURE | {tally.get('FEATURE', 0)} | fabricated feature: test point, "
                f"fiducial or mounting hole. Nothing is bought and nothing is placed |\n")
        f.write(f"\n**{len(rows)} reference designators audited.**\n\n")

        if bad:
            f.write("## Failures\n\n| Ref | MPN | Footprint | Finding | Datasheet |\n"
                    "|---|---|---|---|---|\n")
            for ref, mpn, fp, val, v, pkg, vnote, ds in bad:
                note = "; ".join(x for x in (pkg, vnote) if x)
                f.write(f"| {ref} | `{mpn}` | `{fp}` | {note} | {ds} |\n")
            f.write("\n")
        else:
            f.write("## Failures\n\nNone.\n\n")

        if open_:
            f.write("## Open -- part number is a class, not a part\n\n"
                    "| Ref | MPN | Footprint | Why it cannot be closed here |\n"
                    "|---|---|---|---|\n")
            for ref, mpn, fp, val, v, pkg, vnote, ds in open_:
                f.write(f"| {ref} | `{mpn}` | `{fp}` | {pkg} |\n")
            f.write("\n")

        f.write("## Every designator\n\n")
        f.write("| Ref | Value | Footprint | MPN | Verdict | Package check | Value check |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        for ref, mpn, fp, val, v, pkg, vnote, ds in rows:
            f.write(f"| {ref} | {val} | `{fp}` | `{mpn}` | **{v}** | {pkg} | {vnote} |\n")

        f.write("\n## Datasheets cited\n\n")
        for k in sorted(set(r[7] for r in rows if r[7])):
            f.write(f"- {k}\n")
        f.write("\nNothing in this package has been manufactured or measured, and no part "
                "on this list has been bought, sampled or first-articled.\n")
    return path, tally, bad


if __name__ == "__main__":
    p, tally, bad = write_report()
    print(p)
    for k in ("PASS", "FAIL", "OPEN", "UNRECOGNISED", "FEATURE"):
        print(f"  {k:14s} {tally.get(k, 0)}")
    for r in bad:
        print(f"  {r[4]}  {r[0]:5s} {r[1]:30s} {r[5]} {r[6]}")
