#!/usr/bin/env python3
"""
make_docs.py -- render every Markdown document in package_v2.4/docs to A4 .docx and .pdf.

Pandoc does the Markdown, a generated reference document sets A4 and the house styles, and
LibreOffice makes the PDF.  The Markdown stays in the package as the editable source, so a
correction is made once and both outputs follow.

Licence: CC BY-SA 4.0.
"""
from __future__ import annotations
import os
import re
import subprocess
import sys

import docx_tables

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DOCS = os.path.join(PKG, "docs")
REF = os.path.join(HERE, "reference_A4.docx")
SOFFICE = "/opt/homebrew/bin/soffice"


def make_reference():
    """A4, sensible margins, house fonts and a table style that actually renders.

    This is built FROM PANDOC'S OWN reference document rather than from a blank python-docx
    template, and that is load-bearing.  A reference generated by python-docx is missing
    things pandoc's docx writer depends on, and the visible result was that EVERY TABLE IN
    EVERY DOCUMENT collapsed: LibreOffice abandoned the column layout and printed each cell
    as its own full-width paragraph, so a thirty-row connector table became two hundred and
    forty loose lines spread over eight pages.  Starting from pandoc's own reference keeps
    the styles it writes against ("Table", "Compact", "Author", the caption styles) and we
    override only page geometry, fonts and colours.
    """
    import shutil
    import subprocess as sp
    import zipfile

    base = REF + ".pandoc"
    with open(base, "wb") as fh:
        fh.write(sp.run(["pandoc", "--print-default-data-file", "reference.docx"],
                        check=True, capture_output=True).stdout)

    # A4 with 2.2 cm side margins, in twips
    pgsz = '<w:pgSz w:w="11906" w:h="16838"/>'
    pgmar = ('<w:pgMar w:top="1134" w:right="1247" w:bottom="1134" w:left="1247" '
             'w:header="720" w:footer="720" w:gutter="0"/>')

    tmp = REF + ".tmp"
    with zipfile.ZipFile(base) as zin, \
            zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "word/document.xml":
                x = data.decode("utf8")
                # pandoc's reference carries a bare <w:sectPr> with no page size at
                # all, so these are INSERTED; substituting would silently do nothing and
                # leave the documents on pandoc's default (US Letter) page.
                if "<w:pgSz" in x:
                    x = re.sub(r"<w:pgSz[^/]*/>", pgsz, x)
                    x = re.sub(r"<w:pgMar[^/]*/>", pgmar, x)
                else:
                    x = x.replace("<w:sectPr>", "<w:sectPr>" + pgsz + pgmar, 1)
                assert "<w:pgSz" in x, "page size not set on the reference document"
                data = x.encode("utf8")
            elif item.filename == "word/styles.xml":
                data = _house_styles(data.decode("utf8")).encode("utf8")
            zout.writestr(item, data)
    shutil.move(tmp, REF)
    os.remove(base)
    return REF


def _house_styles(xml):
    """Body and heading fonts, heading colours, and the three table styles."""
    # body text
    xml = re.sub(r'(<w:docDefaults>.*?<w:rPr>)',
                 r'\1<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Calibri"/>'
                 r'<w:sz w:val="21"/><w:szCs w:val="21"/>',
                 xml, count=1, flags=re.S)

    for sid, half_pt, colour in (("Title", 44, "12212E"),
                                 ("Heading1", 30, "12212E"),
                                 ("Heading2", 25, "1B4F72"),
                                 ("Heading3", 22, "1B4F72")):
        def restyle(m, hp=half_pt, col=colour):
            block = m.group(0)
            block = re.sub(r"<w:sz w:val=\"\d+\"\s*/>", "", block)
            block = re.sub(r"<w:szCs w:val=\"\d+\"\s*/>", "", block)
            block = re.sub(r"<w:color[^/]*/>", "", block)
            add = (f'<w:color w:val="{col}"/><w:sz w:val="{hp}"/>'
                   f'<w:szCs w:val="{hp}"/>')
            if "<w:rPr>" in block:
                block = block.replace("<w:rPr>", "<w:rPr>" + add, 1)
            else:
                block = block.replace("</w:style>", f"<w:rPr>{add}</w:rPr></w:style>")
            return block
        xml = re.sub(rf'<w:style [^>]*w:styleId="{sid}".*?</w:style>', restyle,
                     xml, count=1, flags=re.S)

    return docx_tables.install_style(xml)


def convert(md, docx_out, pdf=True):
    cmd = ["pandoc", md, "-o", docx_out, "--reference-doc", REF,
           "--from", "markdown+pipe_tables+backtick_code_blocks+yaml_metadata_block",
           "--toc", "--toc-depth=2", "--standalone"]
    subprocess.run(cmd, check=True)
    docx_tables.process(docx_out)      # widths, autofit, repeating headers -- before the PDF
    if pdf:
        subprocess.run([SOFFICE, "--headless", "--convert-to", "pdf",
                        "--outdir", os.path.dirname(docx_out), docx_out],
                       check=False, capture_output=True)
    return docx_out


def main(pdf=True):
    make_reference()
    made = []
    for f in sorted(os.listdir(DOCS)):
        if not f.endswith(".md"):
            continue
        md = os.path.join(DOCS, f)
        out = md[:-3] + ".docx"
        try:
            convert(md, out, pdf)
            made.append(out)
            print(f"  {f}  ->  {os.path.basename(out)}"
                  + ("  + pdf" if os.path.exists(out[:-5] + ".pdf") else ""))
        except subprocess.CalledProcessError as e:
            print(f"  {f}  FAILED: {e}")
    return made


if __name__ == "__main__":
    make_reference()
    main(pdf="--no-pdf" not in sys.argv)
