#!/usr/bin/env python3
"""
netroutes.py -- the final route of every net: layers, length, via count.

    python3 tools/netroutes.py [routed.pkl] > reports/netroutes.md

Read from the pickle the build wrote; nothing is re-routed here.
Licence: CC BY-SA 4.0.
"""
import math
import os
import pickle
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import design as D   # noqa: E402
import pcbgen        # noqa: E402


def main(path):
    d = pickle.load(open(path, "rb"))
    board = pcbgen.BoardV2()
    nets = board.nets()
    conn = d.get("connectivity", {})
    rows = {}
    for t in d["tracks"]:
        r = rows.setdefault(t.net, dict(F=0.0, B=0.0, seg=0, via=0))
        r["F" if t.layer == "F.Cu" else "B"] += math.hypot(t.x2 - t.x1, t.y2 - t.y1)
        r["seg"] += 1
    for v in d["vias"]:
        rows.setdefault(v.net, dict(F=0.0, B=0.0, seg=0, via=0))["via"] += 1
    print("# Final route of every net")
    print()
    print(f"GENERATED by tools/netroutes.py from {os.path.basename(path)}.  Length is")
    print("centreline copper per layer; the planes (In1/In2) are not tracks and carry")
    print("AGND_REF and DGND -- their pads count vias only.  Status is netcheck's.")
    print()
    print("| net | class | pads | F.Cu mm | B.Cu mm | total mm | vias | segments | status |")
    print("|---|---|---|---|---|---|---|---|---|")
    for net in sorted(nets):
        if len(nets[net]) < 2:
            continue
        r = rows.get(net, dict(F=0.0, B=0.0, seg=0, via=0))
        ok = conn.get(net, (None,))[0]
        status = "connected" if ok else ("OPEN: " + ", ".join(
            s[4:] for s in conn[net][2]) if net in conn else "?")
        layers = "+".join(l for l, k in (("F", "F"), ("B", "B")) if r[k] > 0) or "planes"
        print(f"| {net} | {D.netclass_of(net)} | {len(nets[net])} | {r['F']:.1f} | "
              f"{r['B']:.1f} | {r['F'] + r['B']:.1f} | {r['via']} | {r['seg']} | {status} |")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "routed.pkl"))
