#!/usr/bin/env python3
"""
provision.py -- end-of-line provisioning for the EEG field kit (RFQ F-18).

This is the script the manufacturer runs on every unit, after flashing and after the
functional test has produced its calibration numbers.  It is deliberately boring: it does
one thing per step, prints what it did, refuses to continue if a step fails, and writes a
signed-off record that travels with the unit.

    python3 provision.py --port /dev/ttyACM0 --serial TIOV-B-0007 \
                         --calibration cal_TIOV-B-0007.json \
                         --out records/TIOV-B-0007.json \
                         --write-config --lock

WHAT THIS SCRIPT DOES AND DOES NOT DO
  It does:      write the ATECC608B configuration zone from the template, lock it, generate the
                P-256 key pair inside the element, read back the public key and the chip serial,
                write the USB VID/PID, hardware revision and unit serial, write the calibration
                constants measured at test, verify the lock, and emit the per-unit record.
  It does NOT:  hold, see or transmit the firmware signing key.  The manufacturer flashes an
                image that the programme has already signed (RFQ F-19).  The private device
                key is generated inside the secure element and cannot be read out by anyone,
                including us.

THE TWO IRREVERSIBLE STEPS ARE BOTH BEHIND A FLAG
  ASM-EEG-007 section 6.1 promises that "the script requires an explicit `--lock` and prints
  the scanned board serial back for confirmation", and FW-EEG-001 section 7.2 promises that it
  "rejects any argument that does not match the registered format".  Neither existed: there was
  no `--lock` argument at all -- an operator typing the documented command line got an argparse
  error -- the configuration zone was locked unconditionally at step 8, and `--serial
  NOT-A-SERIAL` was accepted and written into NVS, the ATECC data zone and the record.  Both
  promises are kept here: `--serial` is checked against PKG-EEG-015 section 5, and the lock
  needs `--lock` plus the serial typed or passed back.

THE STEP ORDER IS NOT FW-EEG-001 SECTION 7.3's, AND CANNOT BE
  That table puts GenKey at step 3 and the configuration-zone lock at step 8.  On a
  factory-fresh part the sequence cannot work: the part will not generate a key into a slot
  whose configuration has not been written and locked, so step 3 fails -- and step 8 would then
  lock the default Microchip configuration, permanently scrapping the breakout without ever
  creating the device identity.  The write and the lock therefore run as steps 2b and 2c,
  before GenKey, and old step 8 becomes the read-back that confirms the lock took, which is
  what TST-EEG-004 T6's acceptance limit actually asks for.  Old step 9 read the provisioning
  state with that same 0x48, so the two are printed as one step, `8/9`.  A new step 7b reads the
  calibration constants back and compares them, which is the other half of that limit.  FW-EEG-001 section 7.3 already
  says that where that table and this script differ, the script is what runs; the table still
  needs correcting and that document is not this station's to edit.

TWO THINGS HERE ARE PROPOSALS AND ARE MARKED AS SUCH
  * The configuration-zone template (`atecc608b_config.bin`, generated by
    `atecc608b_config.py`) is a SECURITY decision that nobody has reviewed, and the device
    opcode that writes it does not exist in the shipped firmware.  See
    ATECC608B_CONFIG_TEMPLATE.md, and in particular its reviewer checklist.
  * The calibration file schema (`calibration_schema.py`) fixes key names, units and ranges
    that no document had fixed.  Every key in it is a quantity a numbered test says it records.

WHERE THIS SCRIPT AND THE DOCUMENTS DISAGREE ABOUT NVS, THE FIRMWARE IS THE FACT
  FW-EEG-001 sections 2.5 and 7.3 and ASM-EEG-007 section 6.1 step 5 say the identity goes into
  namespace `eegcfg` in the `prov` partition and the constants into `eegcal` in `calib`.  The
  firmware does not do that.  `main.c` `handle_provision()` writes the keys
  `unit_serial`, `usb_ids`, `hw_rev` and `calib` through `drv_nvs_set_str/blob()`, and
  `drivers.c` lines 435-457 open namespace **"tiov" in the default `nvs` partition** for all of
  them; `prov` and `calib` are declared in partitions.csv, are never initialised and are never
  opened.  This script sends the opcodes, so it writes wherever the firmware puts them: the
  documents are wrong, not the code, and the correction belongs in those documents.  It is not
  cosmetic -- `drivers.c` calls `nvs_flash_erase()` unconditionally on
  ESP_ERR_NVS_NO_FREE_PAGES, so a full default NVS silently erases the unit serial and the
  calibration constants of an already-provisioned instrument.  See README_provisioning.md.

The device must already be running FW-EEG-001 and must enumerate as a CDC-ACM port.
Every command is a COBS-framed CMD frame on that port; the device answers with CMD_ACK.

Licence: MIT.
"""
from __future__ import annotations
import argparse
import binascii
import base64
import hashlib
import json
import os
import re
import struct
import sys
import time

try:
    import serial                       # pyserial
except ImportError:                     # pragma: no cover
    serial = None

try:
    import calibration_schema           # sits next to this file
except ImportError:                     # pragma: no cover
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import calibration_schema

PROTO_VERSION = 1
FT_CMD_ACK = 6

CMD_ENTER_PROVISIONING = 0x40
CMD_ATECC_GENKEY = 0x41
CMD_ATECC_READ_PUBKEY = 0x42
CMD_ATECC_READ_SERIAL = 0x43
CMD_WRITE_USB_IDS = 0x44
CMD_WRITE_HWREV = 0x45
CMD_WRITE_CALIBRATION = 0x46
CMD_ATECC_LOCK_CONFIG = 0x47
CMD_READ_PROVISION_STATE = 0x48
CMD_WRITE_UNIT_SERIAL  = 0x49   # the TIOV-B-nnnn the USB iSerialNumber carries (F-04)

# PROPOSED, and not implemented by the shipped firmware.  `handle_provision()` in
# firmware/main/main.c has no case for either and answers status 0x01.  Both are needed for
# TST-EEG-004 T6 to be executable as it is written; main.c and drivers.c belong to the
# coordinator, so this script sends them, recognises the refusal and says exactly what is
# missing rather than failing obscurely.
CMD_ATECC_WRITE_CONFIG = 0x4B   # payload: block u8 | mask[32] | image[32]   (65 bytes)
#   0x4B, not 0x4A.  Both this file and main.c allocated 0x4A on 2 September 2026 -- here
#   for the config-zone write, there for CMD_READ_CALIBRATION -- because each picked the
#   next free opcode without the other.  The firmware implements 0x4A as the calibration
#   reader, so this moved.  A collision like this answers a config write with a calibration
#   slice and reports success, which is why the opcode table belongs in one place.
CMD_READ_CALIBRATION   = 0x4A   # payload: offset u16 LE | length u8         (3 bytes)
#   0x4A.  This file briefly had BOTH constants at 0x4B: CMD_ATECC_WRITE_CONFIG was moved
#   here to resolve a collision with the firmware, and the move landed on an opcode this
#   file was already using.  A second collision, made while fixing the first, and in the
#   same file rather than across two.  Step 7b would have sent a 3-byte read-back that the
#   firmware parses as a 65-byte config write and answers bad-length, so T6's acceptance
#   read-back would have failed on every unit.  main.c is the authority: 0x4A reads
#   calibration, 0x4B writes the config zone.  provision_selftest.py now asserts that every
#   CMD_ constant in this file is unique, which is the check whose absence let this happen.

CMD_LEAVE_PROVISIONING = 0x4F

# FW-EEG-001 section 6.2 status codes, as far as this script needs them.
ACK_UNKNOWN_OPCODE = 0x01
ACK_LOCKED = 0x09
ACK_NOT_IMPLEMENTED = 0x0B

# FW-EEG-001 section 6.2: an unanswered command is a failure after 2 s; long operations
# (CMD_TIMING_SELFTEST, CMD_ATECC_GENKEY) are given 20 s.
ACK_TIMEOUT_S = 2.0
ACK_TIMEOUT_LONG_S = 20.0

# FW-EEG-001 section 5.1: `n_samples` carries the payload length and is one byte, so a command
# payload is at most 255 bytes including the opcode.  This bites on the calibration write and
# the script says so rather than truncating.
MAX_CMD_PAYLOAD = 255

# main.c rx_poll() accumulates the COBS-encoded frame in `static uint8_t acc[256]` and decodes
# it into `uint8_t out[256]`.  A longer frame is not rejected: the accumulator stops taking
# bytes at 256 (`else if (n < sizeof acc)`), so the frame arrives truncated, fails its CRC and
# is dropped in silence.  That is a tighter ceiling than the n_samples one above, and it is the
# one that actually decides what this station can send.
RX_ACC_BYTES = 256

# Placeholder until the pid.codes allocation arrives.  ECO-EEG-016 tracks it; the value
# must be identical across every unit of a hardware revision or the browser's remembered
# authorisation does not match (RFQ F-03).
DEFAULT_VID = 0x1209
DEFAULT_PID = 0x0001
HW_REV = "B"

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CONFIG_BIN = os.path.join(HERE, "atecc608b_config.bin")
DEFAULT_CONFIG_MASK = os.path.join(HERE, "atecc608b_config.mask.bin")
CONFIG_ZONE_BYTES = 128

# PKG-EEG-015 section 5 is the single home of the serial format and this script cites it rather
# than restating it.  TIOV-B-0000 is excluded because drivers.c unit_serial_into() uses it as
# the "until provisioned" default, so it can never name a real unit.
SERIAL_RE = re.compile(r"^TIOV-B-(\d{4})$")
PHASE_BLOCKS = [(1, 9, "Phase 1"), (10, 99, "Phase 2"), (100, 999, "Phase 3")]

# SubjectPublicKeyInfo DER prefix for an uncompressed P-256 point: SEQUENCE { SEQUENCE {
# id-ecPublicKey 1.2.840.10045.2.1, prime256v1 1.2.840.10045.3.1.7 }, BIT STRING { 04 X Y } }.
# It is a constant for this curve and this point format, which is why the PEM can be built
# here with no library on an offline station.
P256_SPKI_PREFIX = binascii.unhexlify(
    "3059301306072a8648ce3d020106082a8648ce3d03010703420004")


class CommandRefused(IOError):
    """The device answered, and said no.  Carries the FW-EEG-001 section 6.2 status."""

    def __init__(self, opcode, status):
        self.opcode = opcode
        self.status = status
        super().__init__(f"device refused opcode 0x{opcode:02X}, status 0x{status:02X}")


# --------------------------------------------------------------------------- framing
def cobs_encode(data: bytes) -> bytes:
    out = bytearray()
    idx = 0
    while True:
        nxt = data.find(0, idx)
        block = data[idx:] if nxt < 0 else data[idx:nxt]
        while len(block) >= 254:
            out.append(0xFF)
            out += block[:254]
            block = block[254:]
        out.append(len(block) + 1)
        out += block
        if nxt < 0:
            break
        idx = nxt + 1
    out.append(0)
    return bytes(out)


def cobs_decode(data: bytes) -> bytes:
    out = bytearray()
    i = 0
    while i < len(data):
        code = data[i]
        if code == 0:
            break
        out += data[i + 1:i + code]
        if code < 0xFF and i + code < len(data) and data[i + code] != 0:
            out.append(0)
        i += code
    return bytes(out)


def crc32(b: bytes) -> int:
    return binascii.crc32(b) & 0xFFFFFFFF


def command_wire_bytes(cmd, payload):
    """The number of bytes main.c's receive accumulator will hold for this command: the
    COBS-encoded frame without its trailing delimiter.  Computed rather than estimated, because
    COBS overhead depends on where the zero bytes fall in the body."""
    # n_samples is one byte; check_command_fits() rejects an over-long payload before this is
    # called, and the mask keeps this helper from raising struct.error if it ever is not.
    body = struct.pack("<BBHIBB", PROTO_VERSION, 0x10, 0, 0, 0, len(payload) & 0xFF)
    body += bytes([cmd]) + payload
    body += struct.pack("<I", crc32(body))
    return len(body), len(cobs_encode(body)) - 1


def check_command_fits(cmd, payload):
    """Refuse to send a frame the device cannot receive, and say which ceiling it hit."""
    if 1 + len(payload) > MAX_CMD_PAYLOAD:
        raise ValueError(
            f"opcode 0x{cmd:02X}: {1 + len(payload)} payload bytes.  FW-EEG-001 section 5.1 "
            f"carries the payload length in the one-byte n_samples field, so {MAX_CMD_PAYLOAD} "
            f"is the ceiling")
    body_len, wire_len = command_wire_bytes(cmd, payload)
    if body_len > RX_ACC_BYTES or wire_len > RX_ACC_BYTES:
        raise ValueError(
            f"opcode 0x{cmd:02X}: {len(payload)} argument bytes make a {body_len}-byte frame, "
            f"{wire_len} bytes on the wire.  main.c rx_poll() holds {RX_ACC_BYTES} and silently "
            f"drops the rest, so the device would never see this command")


class Device:
    def __init__(self, port, baud=115200, timeout=4.0):
        if serial is None:
            raise SystemExit("pyserial is not installed: pip install pyserial")
        self.s = serial.Serial(port, baud, timeout=timeout)
        self.seq = 0
        time.sleep(0.3)
        self.s.reset_input_buffer()

    def command(self, cmd, payload=b"", deadline=ACK_TIMEOUT_S):
        check_command_fits(cmd, payload)
        # NOTE: this writes `len(payload)` into n_samples, excluding the opcode byte.
        # FW-EEG-001 section 6.1 says n_samples is "payload length" and defines the payload as
        # "the opcode byte followed by its arguments", so the documented value is one larger;
        # webtest/js/protocol.js buildCommand() writes 0.  Three answers, and main.c ignores the
        # field for commands -- rx_poll() dispatches on the decoded body length, not on this
        # byte -- so nothing misbehaves today.  The byte is left exactly as it was rather than
        # changed here: a host header field that three components fill in three different ways
        # is a document decision, not a station one.  README_provisioning.md section 4 item 4.
        body = struct.pack("<BBHIBB", PROTO_VERSION, 0x10, self.seq, 0, 0, len(payload))
        body += bytes([cmd]) + payload
        body += struct.pack("<I", crc32(body))
        self.s.write(b"\x00" + cobs_encode(body))
        self.seq = (self.seq + 1) & 0xFFFF
        return self._read_ack(cmd, deadline)

    def _read_ack(self, opcode, deadline=ACK_TIMEOUT_S):
        t0 = time.time()
        buf = bytearray()
        while time.time() - t0 < deadline:
            b = self.s.read(1)
            if not b:
                continue
            if b == b"\x00":
                if buf:
                    frame = cobs_decode(bytes(buf))
                    buf.clear()
                    if len(frame) < 16:
                        continue
                    if crc32(frame[:-4]) != struct.unpack("<I", frame[-4:])[0]:
                        raise IOError("CRC-32 mismatch on the acknowledgement")
                    if frame[1] == FT_CMD_ACK:
                        status = frame[12]
                        data = frame[14:-4]
                        if status != 0:
                            raise CommandRefused(opcode, status)
                        return data
                continue
            buf += b
        raise TimeoutError(f"no acknowledgement from the device for opcode 0x{opcode:02X} "
                           f"within {deadline:g} s")

    def close(self):
        self.s.close()


# --------------------------------------------------------------------------- checks
def check_serial(serial_no):
    """FW-EEG-001 section 7.2 says this script "rejects any argument that does not match the
    registered format".  The format is PKG-EEG-015 section 5's and this is where it is enforced.
    Returns the phase-block name for the console line."""
    m = SERIAL_RE.match(serial_no or "")
    if not m:
        raise SystemExit(
            f"--serial {serial_no!r} is not a unit serial.\n"
            f"  The format is TIOV-B-nnnn, four digits, defined once in PKG-EEG-015 section 5.\n"
            f"  Serials are allocated by the programme in blocks and issued with the purchase\n"
            f"  order; a manufacturer never invents one.")
    n = int(m.group(1))
    if n == 0:
        raise SystemExit(
            "--serial TIOV-B-0000 is the unprovisioned default that "
            "firmware/main/drivers.c unit_serial_into() writes before provisioning, so it can "
            "never name a real unit.")
    for lo, hi, name in PHASE_BLOCKS:
        if lo <= n <= hi:
            return name
    raise SystemExit(
        f"--serial {serial_no} is outside every block PKG-EEG-015 section 5 allocates "
        f"(0001-0009 Phase 1, 0010-0099 Phase 2, 0100-0999 Phase 3).\n"
        f"  If a further block has been allocated, that is a change to PKG-EEG-015 section 5 "
        f"and to PHASE_BLOCKS in this script, in that order.")


def confirm_serial(serial_no, confirm_arg, dry_run):
    """ASM-EEG-007 section 6.1: "The script requires an explicit --lock and prints the scanned
    board serial back for confirmation."  The barcode scan is the thing most likely to be
    wrong, and the config-zone lock is irreversible, so the operator reads it back."""
    print()
    print("  ---------------------------------------------------------------------------")
    print("  IRREVERSIBLE STEPS AHEAD.  Locking the ATECC608B configuration zone cannot be")
    print("  undone.  A part locked with the wrong template loses the ATECC breakout; J11 is")
    print("  socketed, so hold 10 % spares.  The serial below is written into the USB")
    print("  descriptor, the label, the Data Matrix and the record.")
    print()
    print(f"  scanned unit serial:  {serial_no}")
    print("  ---------------------------------------------------------------------------")
    if dry_run:
        # The rehearsal shows the operator the box they will be asked to read, and then does
        # not ask: a dry run must never be able to block a station waiting on input.
        print("  (dry run: the confirmation is displayed but not asked for)")
        return
    if confirm_arg is not None:
        if confirm_arg != serial_no:
            raise SystemExit(f"--confirm-serial {confirm_arg!r} does not match "
                             f"--serial {serial_no!r}.  Nothing has been written.")
        print("  confirmed by --confirm-serial")
        return
    if not sys.stdin.isatty():
        raise SystemExit(
            "--lock needs the serial confirmed, and this station has no terminal to type it "
            "into.\n  Pass --confirm-serial TIOV-B-nnnn from the test executive instead; it is "
            "the same\n  echo-back and it is recorded the same way.")
    typed = input("  Type the unit serial to confirm, or anything else to abort: ").strip()
    if typed != serial_no:
        raise SystemExit("serial not confirmed.  Nothing has been written.")


def load_config_template(bin_path, mask_path):
    def rd(p):
        with open(p, "rb") as f:
            b = f.read()
        if len(b) != CONFIG_ZONE_BYTES:
            raise SystemExit(f"{p} is {len(b)} bytes; the ATECC608B configuration zone is "
                             f"{CONFIG_ZONE_BYTES}")
        return b
    img, msk = rd(bin_path), rd(mask_path)
    if not any(msk):
        raise SystemExit(f"{mask_path} specifies no bytes at all, so writing the template "
                         f"would do nothing")
    return img, msk, hashlib.sha256(img + msk).hexdigest()


def load_calibration(path, serial_no, override):
    """Read the calibration file, check it against calibration_schema.py, and return
    (constants, wire blob).  A file that does not conform stops the run unless the operator
    passes --calibration-schema-override, which is recorded."""
    with open(path) as f:
        cal = json.load(f)
    problems = calibration_schema.validate(cal, os.path.basename(path))
    if cal.get("example_only") is True:
        raise SystemExit(
            f"{path} has example_only true.  That flag exists so that the shipped template "
            f"cannot be\n  written into a unit as if it were a measurement.  Measure the "
            f"constants and clear it.")
    if isinstance(cal.get("unit_serial"), str) and cal["unit_serial"] != serial_no:
        raise SystemExit(
            f"{path} carries unit_serial {cal['unit_serial']!r} but this run is provisioning "
            f"{serial_no!r}.\n  One of the two is the wrong file.  Nothing has been written.")
    if problems:
        print(f"  calibration file: {len(problems)} problem(s) against "
              f"{calibration_schema.SCHEMA_ID}")
        for p in problems:
            print("    -", p)
        if not override:
            raise SystemExit(
                "  Refusing to write constants that do not conform.  The schema is\n"
                "  firmware/tools/calibration_schema.json, generated by calibration_schema.py, "
                "and it\n  is a PROPOSAL: if it is wrong, fix it there rather than working "
                "around it here.\n  --calibration-schema-override writes the file anyway and "
                "records that it was overridden.")
        print("  --calibration-schema-override given: writing it anyway, and recording that.")
    else:
        print(f"  calibration file: conforms to {calibration_schema.SCHEMA_ID}")
    # `_note` is prose for the person reading the file, not a constant.  The device stores
    # constants; the record keeps the whole file.
    wire = {k: v for k, v in cal.items() if k != "_note"}
    blob = json.dumps(wire, separators=(",", ":"), sort_keys=True).encode()
    return cal, blob


def pubkey_pem(pub: bytes) -> str:
    """TST-EEG-004 T6 "Record" and JIG-EEG-009 section 3.4 "Output" both require the
    uncompressed P-256 public key in PEM; FW-EEG-001 section 7.4 specifies the 128-hex-character
    raw X||Y form.  Both are emitted, because the station is offline and has no tool to convert
    one to the other.  The DER prefix above is fixed for P-256 and an uncompressed point, so no
    library is needed here."""
    if len(pub) != 64:
        raise ValueError(f"a P-256 public key is 64 bytes of X||Y; got {len(pub)}")
    der = P256_SPKI_PREFIX + pub
    b64 = base64.b64encode(der).decode()
    lines = [b64[i:i + 64] for i in range(0, len(b64), 64)]
    return "-----BEGIN PUBLIC KEY-----\n" + "\n".join(lines) + "\n-----END PUBLIC KEY-----\n"


def fingerprint(pub: bytes) -> str:
    """FW-EEG-001 section 7.4 defines it here and nowhere else: the first 8 bytes of SHA-256
    over the 64-byte uncompressed public key, as 16 uppercase hex characters in four groups of
    four.  That grouping is what is printed on the M-03 label and read back at T16."""
    fp = hashlib.sha256(pub).hexdigest()[:16].upper()
    return " ".join(fp[i:i + 4] for i in range(0, 16, 4))


# --------------------------------------------------------------------------- steps
def provision(port, serial_no, calibration, out_path, vid, pid, dry_run=False,
              lock=False, confirm=None, write_config=False,
              config_bin=DEFAULT_CONFIG_BIN, config_mask=DEFAULT_CONFIG_MASK,
              schema_override=False, lock_unwritten_config=False):
    phase = check_serial(serial_no)

    # Locking a configuration zone this station did not write locks whatever the part arrived
    # with.  On a factory-fresh ATECC608B that is the default Microchip configuration, and
    # locking it is the scrap case described in FW-EEG-001 section 7.3 and in
    # ATECC608B_CONFIG_TEMPLATE.md section 5.  The escape hatch is named after what it does, so
    # that nobody reaches for it to make an error message go away.
    if lock and not write_config and not lock_unwritten_config:
        raise SystemExit(
            "--lock without --write-config would lock the configuration zone this station "
            "never wrote.\n"
            "  On a factory-fresh ATECC608B that is the default Microchip configuration: the "
            "lock is\n"
            "  irreversible, the breakout is scrap, and no device identity is ever created.\n"
            "  Pass --write-config as well, or --lock-unwritten-config if the zone was written "
            "by\n  another tool and you have read it back and verified it.")

    # A mistyped --confirm-serial is an argument error and is caught before a device is opened,
    # not half way through the sequence.
    if confirm is not None and confirm != serial_no:
        raise SystemExit(f"--confirm-serial {confirm!r} does not match --serial {serial_no!r}. "
                         f"Nothing has been written.")

    rec = {
        "unit_serial": serial_no,
        "hardware_revision": HW_REV,
        "board": "EEG-CAR-01 Rev B",
        "provisioned_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "station": os.environ.get("STATION", "unknown"),
        "operator": os.environ.get("OPERATOR", "unknown"),
        "usb_vid": f"0x{vid:04X}",
        "usb_pid": f"0x{pid:04X}",
        "phase_block": phase,
        "dry_run": bool(dry_run),
        "steps": [],
    }

    def step(name, fn, optional_reason=None, hints=None):
        print(f"  {name:44s} ", end="", flush=True)
        if dry_run:
            print("skipped (dry run)")
            rec["steps"].append({"step": name, "result": "skipped"})
            return None
        try:
            v = fn()
        except CommandRefused as e:
            if optional_reason and e.status in (ACK_UNKNOWN_OPCODE, ACK_NOT_IMPLEMENTED):
                print(f"NOT AVAILABLE (status 0x{e.status:02X})")
                print(f"       {optional_reason}")
                rec["steps"].append({"step": name, "result": "unavailable",
                                     "detail": f"status 0x{e.status:02X}: {optional_reason}"})
                return None
            print(f"FAILED: {e}")
            if hints and e.status in hints:
                print(f"       {hints[e.status]}")
            rec["steps"].append({"step": name, "result": "fail", "detail": str(e)})
            _write(out_path, rec)
            raise SystemExit(1)
        except Exception as e:
            print(f"FAILED: {e}")
            rec["steps"].append({"step": name, "result": "fail", "detail": str(e)})
            _write(out_path, rec)
            raise SystemExit(1)
        print("ok")
        rec["steps"].append({"step": name, "result": "pass"})
        return v

    print(f"Provisioning {serial_no} on {port}   ({phase})")
    if dry_run:
        print("  DRY RUN: no device is opened and nothing is written.  This is the rehearsal")
        print("  FW-EEG-001 section 7.2 asks for -- it validates the station and the operator")
        print("  before a board exists.")

    # Everything that can be checked without a device is checked before one is touched, so a
    # wrong file or a wrong serial costs nothing.
    cal, blob = ({}, b"")
    if calibration:
        cal, blob = load_calibration(calibration, serial_no, schema_override)
        rec["calibration_file"] = os.path.basename(calibration)
        rec["calibration_schema"] = cal.get("schema")
        if schema_override:
            rec["calibration_schema_override"] = True
        try:
            check_command_fits(CMD_WRITE_CALIBRATION, blob)
        except ValueError as e:
            print()
            print(f"  The calibration blob will not fit in one command frame: {e}.")
            print("  CMD_WRITE_CALIBRATION (0x46) writes the whole payload as one NVS blob in a")
            print("  single frame; there is no chunked form, and the shipped example file is")
            print("  already 1307 bytes minified, so this is not an edge case.")
            print()
            print("  This blocks TST-EEG-004 T6 for any real constant set, and it is a firmware")
            print("  and protocol decision, not a station one.  Two ways out, both the")
            print("  programme's to choose: give 0x46 a leading u16 offset so the blob can be")
            print("  sent in pieces, or define a compact binary encoding of the constants.")
            print("  README_provisioning.md section 4 item 3 states it.")
            raise SystemExit(1)

    template = None
    if write_config:
        template = load_config_template(config_bin, config_mask)
        rec["config_template_sha256"] = template[2]
        rec["config_template"] = os.path.basename(config_bin)
        print(f"  configuration template: {os.path.basename(config_bin)} "
              f"sha256 {template[2][:16]}...")
        print("  PROPOSAL, not reviewed.  See ATECC608B_CONFIG_TEMPLATE.md.")
    else:
        print("  --write-config not given: the configuration zone is left exactly as the part")
        print("  arrived.  On a factory-fresh ATECC608B, step 3 (GenKey) will refuse.")

    if not lock:
        print("  --lock not given: the configuration zone will NOT be locked, so this run")
        print("  cannot produce a finished unit.  Nothing here is irreversible.")

    dev = None if dry_run else Device(port)

    # main.c CMD_ENTER_PROV refuses when the configuration zone is already locked, which is the
    # guard that stops a fielded unit being re-keyed over USB.  It answers 0x02 for it, where
    # FW-EEG-001 section 6.2 assigns 0x02 to "bad length" and 0x09 to "locked", so an operator
    # reading the status table alone would be looking for a framing fault that is not there.
    # Both are hinted here; the code is the fact and the table is what needs correcting.
    already_locked = ("This unit's ATECC608B configuration zone is already locked, so it has "
                      "been\n       provisioned and the firmware refuses to re-key it over USB. "
                      "That is the\n       intended guard, not a fault. If this board is "
                      "genuinely new, the part is not.\n       (main.c answers 0x02 here; "
                      "FW-EEG-001 section 6.2 assigns that code to 'bad\n       length' and "
                      "0x09 to 'locked'. The code is the fact.)")
    step("1  enter provisioning mode",
         lambda: dev.command(CMD_ENTER_PROVISIONING),
         hints={0x02: already_locked, ACK_LOCKED: already_locked})
    atecc_serial = step("2  read the ATECC608B serial number",
                        lambda: dev.command(CMD_ATECC_READ_SERIAL))

    if write_config:
        img, msk, _sha = template

        def write_config_zone():
            for blk in range(CONFIG_ZONE_BYTES // 32):
                lo = blk * 32
                payload = bytes([blk]) + msk[lo:lo + 32] + img[lo:lo + 32]
                if not any(msk[lo:lo + 32]):
                    continue          # nothing in this block is ours; do not touch it
                dev.command(CMD_ATECC_WRITE_CONFIG, payload)
            return True

        wrote_config = step("2b write the configuration zone from the template",
                            write_config_zone,
                            optional_reason=(
                                "The firmware in this unit has no 0x4A opcode.  main.c "
                                "handle_provision() implements\n       0x40-0x49 and 0x4F only, "
                                "and drivers.c exposes no config-zone write.  Nothing has\n"
                                "       been locked, so the part is intact.  This is the "
                                "firmware half of the gap that\n"
                                "       ATECC608B_CONFIG_TEMPLATE.md section 4 specifies; main.c "
                                "and drivers.c are the\n       coordinator's."))
        rec["config_zone_written"] = bool(wrote_config)

        # THE STOP THAT MATTERS.  If the template did not reach the part, the zone still holds
        # whatever the part arrived with -- on a factory-fresh ATECC608B, the default Microchip
        # configuration.  Locking that is the scrap case: it is irreversible, it destroys the
        # breakout, and it produces no device identity.  So the run ends here rather than
        # continuing to step 2c.
        if lock and not wrote_config and not dry_run:
            _write(out_path, rec)
            print()
            print("  STOPPING BEFORE THE LOCK.  The configuration zone was not written, so it")
            print("  still holds whatever the part arrived with.  Locking that is irreversible")
            print("  and scraps the ATECC608B breakout without ever creating a device identity.")
            print("  Nothing irreversible has happened; the part and the board are intact.")
            print("  record ->", out_path)
            raise SystemExit(1)

    # The record is written here, BEFORE anything irreversible, and again at the end.  A run
    # that dies between the lock and the final write would otherwise leave a permanently locked
    # ATECC with no provisioning record and no recoverable identity.
    _write(out_path, rec)

    if lock:
        confirm_serial(serial_no, confirm, dry_run)
        rec["lock_confirmed_by"] = "--confirm-serial" if confirm else "operator typed it back"
        step("2c lock the ATECC608B configuration zone  [IRREVERSIBLE]",
             lambda: dev.command(CMD_ATECC_LOCK_CONFIG))
        _write(out_path, rec)
    else:
        print("  2c lock the ATECC608B configuration zone         SKIPPED (no --lock)")
        rec["steps"].append({"step": "2c lock the configuration zone", "result": "skipped"})

    step("3  generate the P-256 key pair in slot 0",
         lambda: dev.command(CMD_ATECC_GENKEY, bytes([0]), deadline=ACK_TIMEOUT_LONG_S))
    pub = step("4  read back the public key",
               lambda: dev.command(CMD_ATECC_READ_PUBKEY, bytes([0]),
                                   deadline=ACK_TIMEOUT_LONG_S))
    step("5  write the USB vendor and product identifiers",
         lambda: dev.command(CMD_WRITE_USB_IDS, struct.pack("<HH", vid, pid)))
    step("6  write the hardware revision",
         lambda: dev.command(CMD_WRITE_HWREV, HW_REV.encode()))

    # The unit serial was previously carried only in this script's JSON record and its
    # console output -- it never reached the device, so the USB iSerialNumber stayed at the
    # unprovisioned default and the browser had nothing stable to bind its authorisation
    # to.  RUL-EEG-021 section B makes TIOV-B-nnnn the descriptor string, so it has to be
    # written into NVS here.
    step("6b write the unit serial into the device",
         lambda: dev.command(CMD_WRITE_UNIT_SERIAL, serial_no.encode()))

    if calibration:
        step("7  write the calibration constants",
             lambda: dev.command(CMD_WRITE_CALIBRATION, blob))

        # TST-EEG-004 T6's acceptance limit is "constants read back byte-identical to those
        # written".  Nothing in the package could read them back: 0x48 returns two flag bytes
        # and there is no read opcode for the calibration blob, the USB identifiers, the
        # hardware revision or the unit serial.  This step is the verification T6 asks for; it
        # needs the proposed 0x4B.
        def read_back_calibration():
            got = bytearray()
            while len(got) < len(blob):
                want = min(200, len(blob) - len(got))
                chunk = dev.command(CMD_READ_CALIBRATION,
                                    struct.pack("<HB", len(got), want))
                if not chunk:
                    raise IOError(f"read-back returned nothing at offset {len(got)}")
                got += chunk
            if bytes(got) != blob:
                raise IOError("the constants read back are not byte-identical to those "
                              "written, which is TST-EEG-004 T6's acceptance limit")
            return True

        ok = step("7b read the calibration constants back and compare", read_back_calibration,
                  optional_reason=(
                      "The firmware in this unit has no 0x4B opcode, so the constants cannot be "
                      "read\n       back and T6's acceptance limit -- 'constants read back "
                      "byte-identical to those\n       written' -- is NOT demonstrated on this "
                      "unit.  The write itself succeeded.\n       main.c is the coordinator's."))
        rec["calibration_readback_verified"] = bool(ok) and not dry_run
    else:
        print("  7  write the calibration constants                 SKIPPED "
              "(no --calibration given)")
        rec["steps"].append({"step": "7 calibration", "result": "skipped"})

    # Old step 8 was the lock itself.  The lock has to happen before GenKey (see the header), so
    # what is left at 8 is the read-back that proves it took -- which is what T6's acceptance
    # limit asks for.  FW-EEG-001's step 9 read the provisioning state with the same 0x48, and
    # one command answers both questions, so the two are one step and keep both numbers rather
    # than sending an identical command twice with nothing in between.
    state = step("8/9 read the state back and confirm the lock",
                 lambda: dev.command(CMD_READ_PROVISION_STATE))
    if state is not None and len(state) >= 1:
        locked = state[0] == 1
        rec["config_zone_locked"] = locked
        if lock and not locked:
            print("       THE CONFIGURATION ZONE READS UNLOCKED AFTER THE LOCK STEP.")
            print("       This unit is not provisioned.  Hold it and report it: a lock that")
            print("       reports success and does not take is a firmware or a part fault.")
    step("10 leave provisioning mode",
         lambda: dev.command(CMD_LEAVE_PROVISIONING))
    if dev:
        dev.close()

    if pub:
        rec["device_public_key"] = binascii.hexlify(pub).decode()
        # RUL-EEG-021 section B and FW-EEG-001 section 7.4 both require the fingerprint to be
        # DISPLAYED in four groups of four, which is how it is printed on the label and how
        # an operator reads it back at T16.  The bytes were right and the grouping was not.
        #
        # This block used to sit one level out, so on any run where step 4 returned no public
        # key -- every --dry-run, and any live run where the read failed -- it hashed None and
        # died with "object supporting the buffer API required", after step 8 had already
        # locked the configuration zone and before the record was written.
        rec["public_key_fingerprint"] = fingerprint(pub)
        try:
            rec["device_public_key_pem"] = pubkey_pem(pub)
        except ValueError as e:
            rec["device_public_key_pem_error"] = str(e)
    if atecc_serial:
        rec["atecc_serial"] = binascii.hexlify(atecc_serial).decode().upper()
    if state:
        rec["provision_state"] = binascii.hexlify(state).decode()
    rec["calibration"] = cal
    _write(out_path, rec)

    print()
    print("  unit serial            ", rec["unit_serial"])
    print("  ATECC serial           ", rec.get("atecc_serial", "-"))
    print("  public key fingerprint ", rec.get("public_key_fingerprint", "-"))
    print("  public key (PEM)       ", "yes" if rec.get("device_public_key_pem") else "-")
    print()
    print("  Print the fingerprint on the enclosure label (RFQ M-03) and return this")
    print("  record with the unit.  The private key stays inside the secure element and")
    print("  cannot be read by anyone, including us.")
    print("  record ->", out_path)
    if not dry_run and not rec.get("config_zone_locked"):
        print()
        print("  THIS UNIT IS NOT FINISHED: the ATECC608B configuration zone is not locked, so")
        print("  the device identity can still be replaced.  Do not pass T6 on this record.")
    return rec


def _write(path, rec):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        json.dump(rec, f, indent=2, sort_keys=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--port", required=True, help="CDC-ACM port of the unit")
    ap.add_argument("--serial", required=True,
                    help="unit serial, TIOV-B-nnnn (PKG-EEG-015 section 5)")
    ap.add_argument("--calibration", help="JSON of the constants measured at functional test; "
                                          "the schema is calibration_schema.json")
    ap.add_argument("--out", default=None, help="where to write the per-unit record")
    ap.add_argument("--vid", type=lambda s: int(s, 0), default=DEFAULT_VID)
    ap.add_argument("--pid", type=lambda s: int(s, 0), default=DEFAULT_PID)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the sequence without touching a device")
    ap.add_argument("--lock", action="store_true",
                    help="permit the IRREVERSIBLE configuration-zone lock. The serial must be "
                         "confirmed as well, by typing it back or with --confirm-serial")
    ap.add_argument("--confirm-serial", default=None, metavar="TIOV-B-nnnn",
                    help="echo the scanned serial back non-interactively, for a station with no "
                         "terminal")
    ap.add_argument("--write-config", action="store_true",
                    help="write the ATECC608B configuration-zone template before locking. The "
                         "template is a PROPOSAL and has not been reviewed: read "
                         "ATECC608B_CONFIG_TEMPLATE.md first")
    ap.add_argument("--config-template", default=DEFAULT_CONFIG_BIN,
                    help="the 128-byte configuration-zone image (default: the shipped template)")
    ap.add_argument("--config-mask", default=DEFAULT_CONFIG_MASK,
                    help="the 128-byte mask saying which of those bytes to write")
    ap.add_argument("--lock-unwritten-config", action="store_true",
                    help="permit --lock without --write-config, for a zone written by another "
                         "tool and read back and verified. Without it, --lock requires "
                         "--write-config")
    ap.add_argument("--calibration-schema-override", action="store_true",
                    help="write a calibration file that does not conform to the schema, and "
                         "record that it was overridden")
    a = ap.parse_args()
    out = a.out or f"records/{a.serial}.json"
    provision(a.port, a.serial, a.calibration, out, a.vid, a.pid, a.dry_run,
              lock=a.lock, confirm=a.confirm_serial, write_config=a.write_config,
              config_bin=a.config_template, config_mask=a.config_mask,
              schema_override=a.calibration_schema_override,
              lock_unwritten_config=a.lock_unwritten_config)


if __name__ == "__main__":
    main()
